name: gsasii
channels:
  - diffpy
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.15
  - pip=24.2
  - pybind11-abi=4
  - python=3.11.9
  - readline=8.2
  - scipy=1.13.1
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
